language: python
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  # PyPy versions
#  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
#  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
#  - pip install flake8
# command to run tests
script:
  #  - flake8
  - pytest -v
after_success:
  - coveralls